apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomzation
namespace: demo   # 모든 리소스에 demo네임스페이스 적용

# demo 네임 스페이스에 포함시킬 목록
resources:
  - gitops-namespace.yaml
  - gitops-configmap.yaml
  - gitops-mysql-depolment.yaml
  - gitops-mysql-serivce.yaml
  - gitops-deployment.yaml
  - gitops-service.yaml

images:
- name: docekr/io/maranqian/demo
  newName: docker.io/maranqian.demo
  newTag: 958b985